USE [korona2]
GO
/****** Object:  Table [dbo].[J_ARCHIVE_TBL]    Script Date: 14/04/2021 20:41:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[J_ARCHIVE_TBL](
	[GERM_ID] [int] NOT NULL,
	[MEDICINE_ID] [int] NOT NULL,
	[GERM_NAME] [varchar](20) NOT NULL,
	[MEDICINE_NAME] [varchar](20) NULL,
	[TEST_DATE] [datetime] NOT NULL,
	[REACTION_TYPE] [varchar](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[GERM_ID] ASC,
	[MEDICINE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[J_EXCEPTION_TBL]    Script Date: 14/04/2021 20:41:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[J_EXCEPTION_TBL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MESSAGES] [varchar](300) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[J_JERMS_TBL]    Script Date: 14/04/2021 20:41:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[J_JERMS_TBL](
	[ID] [int] NOT NULL,
	[J_NAME] [varchar](20) NOT NULL,
	[SHORT_DESC] [varchar](50) NULL,
	[ID_date] [datetime] NOT NULL,
	[MEDICINE_DATE] [datetime] NULL,
	[MEDICINE_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[J_MEDICINE_TBL]    Script Date: 14/04/2021 20:41:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[J_MEDICINE_TBL](
	[ID] [int] NOT NULL,
	[M_NAME] [varchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[J_TEST_TBL]    Script Date: 14/04/2021 20:41:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[J_TEST_TBL](
	[GERM_ID] [int] NOT NULL,
	[MEDICINE_ID] [int] NOT NULL,
	[TEST_DATE] [datetime] NOT NULL,
	[REACTION_TYPE] [varchar](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[GERM_ID] ASC,
	[MEDICINE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[J_ARCHIVE_TBL] ([GERM_ID], [MEDICINE_ID], [GERM_NAME], [MEDICINE_NAME], [TEST_DATE], [REACTION_TYPE]) VALUES (3, 452, N'Korona1', NULL, CAST(N'2020-01-01T00:00:00.000' AS DateTime), N'ALIVE')
GO
INSERT [dbo].[J_ARCHIVE_TBL] ([GERM_ID], [MEDICINE_ID], [GERM_NAME], [MEDICINE_NAME], [TEST_DATE], [REACTION_TYPE]) VALUES (8, 22, N'Korona1', NULL, CAST(N'2020-02-02T00:00:00.000' AS DateTime), N'DEAD')
GO
INSERT [dbo].[J_ARCHIVE_TBL] ([GERM_ID], [MEDICINE_ID], [GERM_NAME], [MEDICINE_NAME], [TEST_DATE], [REACTION_TYPE]) VALUES (1234, 4566, N'aaa', N'aba', CAST(N'2003-10-10T00:00:00.000' AS DateTime), N'ALIVE')
GO
INSERT [dbo].[J_ARCHIVE_TBL] ([GERM_ID], [MEDICINE_ID], [GERM_NAME], [MEDICINE_NAME], [TEST_DATE], [REACTION_TYPE]) VALUES (2344, 6432, N'bb', N'bba', CAST(N'2020-02-05T00:00:00.000' AS DateTime), N'ALIVE')
GO
SET IDENTITY_INSERT [dbo].[J_EXCEPTION_TBL] ON 
GO
INSERT [dbo].[J_EXCEPTION_TBL] ([ID], [MESSAGES]) VALUES (1, N'ADD_TEXT_SQLSubquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.ניסוי זה כבר קיים ')
GO
INSERT [dbo].[J_EXCEPTION_TBL] ([ID], [MESSAGES]) VALUES (2, N'ADD_TEXT_SQLSubquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.ניסוי זה כבר קיים ')
GO
SET IDENTITY_INSERT [dbo].[J_EXCEPTION_TBL] OFF
GO
INSERT [dbo].[J_JERMS_TBL] ([ID], [J_NAME], [SHORT_DESC], [ID_date], [MEDICINE_DATE], [MEDICINE_ID]) VALUES (1, N'kovid19', NULL, CAST(N'2020-01-01T00:00:00.000' AS DateTime), NULL, 100)
GO
INSERT [dbo].[J_JERMS_TBL] ([ID], [J_NAME], [SHORT_DESC], [ID_date], [MEDICINE_DATE], [MEDICINE_ID]) VALUES (2, N'Atalef19', N'very slim', CAST(N'2020-05-22T00:00:00.000' AS DateTime), NULL, 101)
GO
INSERT [dbo].[J_JERMS_TBL] ([ID], [J_NAME], [SHORT_DESC], [ID_date], [MEDICINE_DATE], [MEDICINE_ID]) VALUES (3, N'Korona1', N'VERY OLD', CAST(N'2019-08-30T00:00:00.000' AS DateTime), NULL, 102)
GO
INSERT [dbo].[J_JERMS_TBL] ([ID], [J_NAME], [SHORT_DESC], [ID_date], [MEDICINE_DATE], [MEDICINE_ID]) VALUES (4, N'Korona2', NULL, CAST(N'2021-05-02T00:00:00.000' AS DateTime), NULL, 103)
GO
INSERT [dbo].[J_JERMS_TBL] ([ID], [J_NAME], [SHORT_DESC], [ID_date], [MEDICINE_DATE], [MEDICINE_ID]) VALUES (5, N'chorfan', N'new', CAST(N'2018-05-05T00:00:00.000' AS DateTime), NULL, 104)
GO
INSERT [dbo].[J_JERMS_TBL] ([ID], [J_NAME], [SHORT_DESC], [ID_date], [MEDICINE_DATE], [MEDICINE_ID]) VALUES (6, N'chorfan', N'new', CAST(N'2018-05-05T00:00:00.000' AS DateTime), NULL, 104)
GO
INSERT [dbo].[J_JERMS_TBL] ([ID], [J_NAME], [SHORT_DESC], [ID_date], [MEDICINE_DATE], [MEDICINE_ID]) VALUES (7, N'Korona2', NULL, CAST(N'2021-05-02T00:00:00.000' AS DateTime), NULL, 103)
GO
INSERT [dbo].[J_JERMS_TBL] ([ID], [J_NAME], [SHORT_DESC], [ID_date], [MEDICINE_DATE], [MEDICINE_ID]) VALUES (8, N'Korona1', N'VERY OLD', CAST(N'2019-08-30T00:00:00.000' AS DateTime), CAST(N'2020-02-02T00:00:00.000' AS DateTime), 102)
GO
INSERT [dbo].[J_JERMS_TBL] ([ID], [J_NAME], [SHORT_DESC], [ID_date], [MEDICINE_DATE], [MEDICINE_ID]) VALUES (9, N'Atalef19', N'very slim', CAST(N'2020-05-22T00:00:00.000' AS DateTime), NULL, 101)
GO
INSERT [dbo].[J_JERMS_TBL] ([ID], [J_NAME], [SHORT_DESC], [ID_date], [MEDICINE_DATE], [MEDICINE_ID]) VALUES (1439, N'kovid19', N'hgj', CAST(N'2020-01-01T00:00:00.000' AS DateTime), NULL, 1005)
GO
INSERT [dbo].[J_JERMS_TBL] ([ID], [J_NAME], [SHORT_DESC], [ID_date], [MEDICINE_DATE], [MEDICINE_ID]) VALUES (5478, N'xxx', N'ert', CAST(N'2020-02-05T00:00:00.000' AS DateTime), NULL, 8765)
GO
INSERT [dbo].[J_MEDICINE_TBL] ([ID], [M_NAME]) VALUES (1, N'VITAMIND')
GO
INSERT [dbo].[J_MEDICINE_TBL] ([ID], [M_NAME]) VALUES (2, N'KOKTEL')
GO
INSERT [dbo].[J_MEDICINE_TBL] ([ID], [M_NAME]) VALUES (3, N'PENITZILINE')
GO
INSERT [dbo].[J_MEDICINE_TBL] ([ID], [M_NAME]) VALUES (4, N'SPARIN')
GO
INSERT [dbo].[J_MEDICINE_TBL] ([ID], [M_NAME]) VALUES (5, N'VITAMIND')
GO
INSERT [dbo].[J_MEDICINE_TBL] ([ID], [M_NAME]) VALUES (6, N'KOKTEL')
GO
INSERT [dbo].[J_MEDICINE_TBL] ([ID], [M_NAME]) VALUES (7, N'PENITZILINE')
GO
INSERT [dbo].[J_MEDICINE_TBL] ([ID], [M_NAME]) VALUES (8, N'SPARIN')
GO
INSERT [dbo].[J_MEDICINE_TBL] ([ID], [M_NAME]) VALUES (11, N'ddd')
GO
INSERT [dbo].[J_TEST_TBL] ([GERM_ID], [MEDICINE_ID], [TEST_DATE], [REACTION_TYPE]) VALUES (1, 100, CAST(N'1901-05-21T00:00:00.000' AS DateTime), N'dying')
GO
INSERT [dbo].[J_TEST_TBL] ([GERM_ID], [MEDICINE_ID], [TEST_DATE], [REACTION_TYPE]) VALUES (1, 333, CAST(N'2020-01-01T00:00:00.000' AS DateTime), N'ALIVE')
GO
INSERT [dbo].[J_TEST_TBL] ([GERM_ID], [MEDICINE_ID], [TEST_DATE], [REACTION_TYPE]) VALUES (1, 452, CAST(N'2020-01-01T00:00:00.000' AS DateTime), N'ALIVE')
GO
INSERT [dbo].[J_TEST_TBL] ([GERM_ID], [MEDICINE_ID], [TEST_DATE], [REACTION_TYPE]) VALUES (1, 456, CAST(N'2020-01-01T00:00:00.000' AS DateTime), N'ALIVE')
GO
INSERT [dbo].[J_TEST_TBL] ([GERM_ID], [MEDICINE_ID], [TEST_DATE], [REACTION_TYPE]) VALUES (2, 487, CAST(N'2020-05-01T00:00:00.000' AS DateTime), N'ALIVE')
GO
INSERT [dbo].[J_TEST_TBL] ([GERM_ID], [MEDICINE_ID], [TEST_DATE], [REACTION_TYPE]) VALUES (2, 533, CAST(N'2020-05-01T00:00:00.000' AS DateTime), N'ALIVE')
GO
INSERT [dbo].[J_TEST_TBL] ([GERM_ID], [MEDICINE_ID], [TEST_DATE], [REACTION_TYPE]) VALUES (2, 999, CAST(N'2020-05-01T00:00:00.000' AS DateTime), N'ALIVE')
GO
INSERT [dbo].[J_TEST_TBL] ([GERM_ID], [MEDICINE_ID], [TEST_DATE], [REACTION_TYPE]) VALUES (4, 31, CAST(N'2020-01-01T00:00:00.000' AS DateTime), N'dead')
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [cnt]    Script Date: 14/04/2021 20:41:09 ******/
ALTER TABLE [dbo].[J_JERMS_TBL] ADD  CONSTRAINT [cnt] UNIQUE NONCLUSTERED 
(
	[ID] ASC,
	[J_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [cont]    Script Date: 14/04/2021 20:41:09 ******/
ALTER TABLE [dbo].[J_MEDICINE_TBL] ADD  CONSTRAINT [cont] UNIQUE NONCLUSTERED 
(
	[ID] ASC,
	[M_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[J_ARCHIVE_TBL] ADD  DEFAULT ('ALIVE') FOR [REACTION_TYPE]
GO
ALTER TABLE [dbo].[J_TEST_TBL] ADD  DEFAULT ('ALIVE') FOR [REACTION_TYPE]
GO
ALTER TABLE [dbo].[J_ARCHIVE_TBL]  WITH CHECK ADD  CONSTRAINT [enum_co] CHECK  (([REACTION_TYPE]='DYING' OR [REACTION_TYPE]='DEAD' OR [REACTION_TYPE]='ALIVE'))
GO
ALTER TABLE [dbo].[J_ARCHIVE_TBL] CHECK CONSTRAINT [enum_co]
GO
ALTER TABLE [dbo].[J_TEST_TBL]  WITH CHECK ADD  CONSTRAINT [enum_const] CHECK  (([REACTION_TYPE]='DYING' OR [REACTION_TYPE]='DEAD' OR [REACTION_TYPE]='ALIVE'))
GO
ALTER TABLE [dbo].[J_TEST_TBL] CHECK CONSTRAINT [enum_const]
GO
